[build]
    builder = "DOCKERFILE"
    dockerfilePath = "Dockerfile.dev"

[deploy]
    startCommand = "sh -c 'nginx && pnpm run pm2'"
    restartPolicyType = "ON_FAILURE"
    restartPolicyMaxRetries = 10
    healthcheckPath = "/api/health"
    healthcheckTimeout = 600